apiVersion: skaffold/v2beta25
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ahmed0ahmed/racer-positions
      context: positions
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest : .
    - image: ahmed0ahmed/racer-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ahmed0ahmed/racer-races
      context: races
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ahmed0ahmed/racer-archive
      context: archive
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ahmed0ahmed/racer-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
 
 