[project]
name = "predictions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncio-nats-streaming>=0.4.0",
    "fastapi>=0.141.1",
    "protobuf<3.21",
    "torch>=2.13.0",
    "uvicorn>=0.52.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cpu"
