#section that create the deployment and the pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: positions-depl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: positions
  template: 
    metadata:
      labels:
        app: positions
    spec:
      containers:
        - name: positions
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          image: ahmed0ahmed/racer-positions
          imagePullPolicy : Never
          env: 
            - name: NATS_CLUSTER_ID
              value: 'racer.io'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef: 
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'nats://nats-srv:4222'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: REDIS_HOST
              value: positions-redis-srv
---
#kubernets service cluesterip so we can acess the pod
#default service is clusterip service that why we didint have to
#specifie it
apiVersion: v1
kind: Service
metadata: 
  name: positions-srv
spec: 
  selector:
    app: positions
  ports:
    - name: positions
      protocol: TCP
      port: 3000
      targetPort: 3000
